# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = androidAlertAgent
OBJS = androidAlertAgent.o

include $(TOPDIR)/applications/Rules.mak
