# Makefile for androiRoot micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = androidRootAgent
OBJS = androidRootAgent.o

include $(TOPDIR)/applications/Rules.mak
