/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lekkas_poclient_PoMainA */

#ifndef _Included_org_lekkas_poclient_PoMainA
#define _Included_org_lekkas_poclient_PoMainA
#ifdef __cplusplus
extern "C" {
#endif

JNIEnv *jni_env;
jobject jni_MainA_obj;

/*
 * Class:     org_lekkas_poclient_PoMainA
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lekkas_poclient_PoAPI_MiddlewareInterface_stringFromJNI
  (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_org_lekkas_poclient_PoAPI_MiddlewareInterface_poMain
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
